### ISSUE TITLE
Twitter voting with ethereum integration

### ISSUE THREAD

**Issue by aquabu** [CoMakery/comakery-app#131]
Rough feature description:
- [ ] Link on project show page says "Vote For This Project"
- [ ] When a user clicks it pre-populates a twitter vote which says:
``@DigiCatapult I'm voting for @comakery-project-id`` (@DigiCatapult is the twitter id associated with the slack instance of the project)
- [ ] Each vote issues a blockchain vote
- [ ] The blockchain votes are summarized per slack instance and for the whole comakery-app

UI design pending.

**Comment by harlantwood** [comment]
Goals
- show votes in blockchain
- easy login

# 2. 

- auth w/ twitter
- prepopulated  tweet : @DigiCatapult I'm voting for 
  @comakery-project-url 
- you must tweet to vote.
- we check for @DigiCatapult mentions from ruby 
- increment smart contract vote counts

# 3.

- "vote" w/ community awards
  - all must be in same slack instance 
- they create 1 project per hackathon project
- distribute dividends (eth) to all ppl w/ eth addrss in all projects in instance
- distribute ether via smart contract

# 4.

- blockchain computer
- authed to 1 slack inst
- hackathon teams create 1 "project" per team
- anyone can issue awards to projects in instance as well as ppl
- project award is auto split immediately into ppl awards, by current cap table

## stories for 4.
- dividend dist
- project address dist table
- send award to project

# 5.

- log in with ethereum
